// <auto-generated />
using System;
using IntroSEProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntroSEProject.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231209144657_m3")]
    partial class m3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IntroSEProject.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("IntroSEProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hic provident voluptate et occaecati aperiam placeat sapiente. Quas aut non quae voluptas ratione voluptas impedit similique ut.",
                            Name = "Autem commodi qui.",
                            Thumbnail = "https://picsum.photos/640/480/?image=233"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dolores mollitia distinctio adipisci ad doloribus minus corporis occaecati. Perferendis in et est ut. Iste temporibus ducimus nam omnis. Eligendi quia rerum libero quibusdam magni velit et id eos.",
                            Name = "Qui numquam qui.",
                            Thumbnail = "https://picsum.photos/640/480/?image=134"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nobis sint quasi tempora cupiditate velit magni placeat repellendus.",
                            Name = "Ducimus accusantium odio.",
                            Thumbnail = "https://picsum.photos/640/480/?image=597"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Adipisci eaque dolores et blanditiis nemo est adipisci id odit. Dolorum debitis accusantium voluptatum culpa.",
                            Name = "Sint accusamus voluptas.",
                            Thumbnail = "https://picsum.photos/640/480/?image=1042"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Provident voluptatum veniam architecto eos aut quo. Voluptas in enim consectetur. Velit non sed harum praesentium. Voluptatem totam quia.",
                            Name = "Dolorem temporibus odit.",
                            Thumbnail = "https://picsum.photos/640/480/?image=986"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Aut nihil illo voluptatem sit id. Voluptatem dolorum vel ipsum qui ex reprehenderit.",
                            Name = "Temporibus aliquam est.",
                            Thumbnail = "https://picsum.photos/640/480/?image=263"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Illo quis provident. Doloremque laborum quia velit incidunt. Qui esse similique blanditiis sed dolorum.",
                            Name = "Debitis enim nobis.",
                            Thumbnail = "https://picsum.photos/640/480/?image=843"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Repudiandae aliquam nostrum ut sapiente architecto nisi. Deleniti similique illo magnam quia. Quia est nostrum voluptate deleniti sunt temporibus magni. Possimus nesciunt ut consectetur sequi provident voluptatem.",
                            Name = "Doloribus quia facere.",
                            Thumbnail = "https://picsum.photos/640/480/?image=378"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Eaque nobis est ab quasi. Perferendis aliquam ea voluptatem magni similique ducimus dolorum cumque.",
                            Name = "Sint sequi unde.",
                            Thumbnail = "https://picsum.photos/640/480/?image=555"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Provident amet veritatis rerum amet fugiat nesciunt illo. Explicabo omnis quia saepe. Id omnis et voluptatem et fugit ullam qui. Assumenda fuga impedit voluptates dolorum maxime facilis suscipit fugiat.",
                            Name = "Ad illum porro.",
                            Thumbnail = "https://picsum.photos/640/480/?image=832"
                        });
                });

            modelBuilder.Entity("IntroSEProject.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Images")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Neque aut aperiam at sed modi modi ex reprehenderit omnis recusandae explicabo consequatur voluptas quibusdam autem libero qui eos ut.",
                            Discount = 10.2625183897384060m,
                            Name = "Quas dolores qui.",
                            Price = 10.2963503856660570m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=630"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Possimus rerum et ipsam amet aut dolor ut qui necessitatibus quaerat aspernatur quia et velit incidunt sequi aut non id.",
                            Discount = 10.5412858498940640m,
                            Name = "Sed enim dolores.",
                            Price = 10.7996915331108920m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=1004"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Quis ut in odit voluptatem necessitatibus qui laudantium velit necessitatibus labore maxime voluptatibus eum in et et voluptate exercitationem delectus.",
                            Discount = 10.8842109040749310m,
                            Name = "Sit commodi voluptatem.",
                            Price = 10.7302641648474450m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=5"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Eligendi eius et dolores magni qui sapiente necessitatibus consequatur maxime dolor earum non dignissimos voluptatem alias nisi sint tempora unde.",
                            Discount = 10.2241724879593460m,
                            Name = "Hic consequatur sunt.",
                            Price = 10.9056787346050510m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=354"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Quam ea accusamus architecto nesciunt enim voluptatem aperiam dolore quas reprehenderit odit molestiae voluptatem earum non voluptates consequuntur totam dicta.",
                            Discount = 10.5782992362875020m,
                            Name = "Mollitia necessitatibus in.",
                            Price = 10.5199016712232970m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=143"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Libero rem voluptas est ut et quam ut corrupti dolores tempore fuga et necessitatibus velit et et hic consequatur corporis.",
                            Discount = 10.9647345128304950m,
                            Name = "Velit quisquam praesentium.",
                            Price = 10.5237351872603110m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=745"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Aut voluptas occaecati sit distinctio iusto at et error sint qui quos et quas deleniti qui quo labore quas quo.",
                            Discount = 10.1093169958839740m,
                            Name = "Consequatur magni et.",
                            Price = 10.1964963391406910m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=1062"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Itaque cumque blanditiis aliquid assumenda assumenda odio ut cumque ut enim aut amet omnis labore nulla maiores est praesentium earum.",
                            Discount = 10.04209549307920760m,
                            Name = "Id animi quam.",
                            Price = 10.7963249775563950m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=415"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Id est dolorem eos ducimus veritatis perferendis sint hic odit similique sapiente quisquam nihil delectus dolor atque in incidunt ipsam.",
                            Discount = 10.9568571205981340m,
                            Name = "Quod quas nostrum.",
                            Price = 10.06344848129127570m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=328"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fuga saepe consectetur voluptatem est voluptatem deleniti quo voluptas provident eum et hic quia eos nostrum quod quam consequatur id.",
                            Discount = 10.8291591614620570m,
                            Name = "Laborum minima expedita.",
                            Price = 10.5186430129775050m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=745"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Tempora est molestias deleniti cupiditate ipsum ea reprehenderit voluptatem possimus tenetur a optio labore officia velit dolore et provident veniam.",
                            Discount = 10.2035620613971550m,
                            Name = "Ut molestias consectetur.",
                            Price = 10.1409733831607610m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=29"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Eos autem harum neque magnam aspernatur architecto aliquam amet quaerat ab corporis optio perspiciatis repellendus quo provident repellendus praesentium fugit.",
                            Discount = 10.9305860870194560m,
                            Name = "Ut et ut.",
                            Price = 10.4976657640643720m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=567"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Ab voluptatem voluptatibus maiores non est et voluptatem mollitia iure deserunt nihil vero fuga maiores in earum velit ut quo.",
                            Discount = 10.3572064481476350m,
                            Name = "Quis quis tempora.",
                            Price = 10.7361000388563140m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=12"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Ipsa non dolorem dolorum autem aut officiis accusantium incidunt quia enim voluptas culpa et veniam amet qui itaque beatae id.",
                            Discount = 10.5130112019893770m,
                            Name = "Quod consequatur est.",
                            Price = 10.4902248785319850m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=143"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Quos eligendi expedita pariatur dolore ea eaque officia illo molestiae voluptas et dolorem maiores animi facere consectetur tempore ex assumenda.",
                            Discount = 10.4521177147757810m,
                            Name = "Vel voluptatem provident.",
                            Price = 10.7715774889903040m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=744"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Velit non cum deleniti consequatur assumenda ut vel suscipit in ea voluptatem iusto perspiciatis deleniti incidunt omnis nobis eos magnam.",
                            Discount = 10.8917455817068670m,
                            Name = "Adipisci distinctio sed.",
                            Price = 10.61712907562830m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=992"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Omnis eaque cupiditate quod expedita qui velit voluptas inventore autem hic a aperiam deleniti id voluptatem dolor fugiat est et.",
                            Discount = 10.2934667613792540m,
                            Name = "Perferendis blanditiis aliquam.",
                            Price = 10.2260272005694110m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=367"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Officia corporis assumenda laboriosam totam aliquid sint officia laboriosam consequatur fugiat cumque iusto ut cumque quam vero consequatur qui aut.",
                            Discount = 10.01217651647151290m,
                            Name = "Incidunt inventore velit.",
                            Price = 10.772347067376760m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=443"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Doloremque totam illum fugit excepturi animi quia laborum sed nostrum aperiam atque est occaecati necessitatibus voluptatem blanditiis nisi dolores non.",
                            Discount = 10.5239242629725130m,
                            Name = "Quas commodi sed.",
                            Price = 10.6876236846147220m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=633"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Rerum in cum sit quo aut vel corrupti quia cupiditate optio voluptatem aut voluptatem dolorum dolorem magni qui voluptas sed.",
                            Discount = 10.8813037503889310m,
                            Name = "Mollitia quas tenetur.",
                            Price = 10.5830614453102750m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=395"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Pariatur quas deserunt blanditiis sint aut facilis sed eaque vero odit velit vel autem aperiam assumenda quod possimus accusantium doloremque.",
                            Discount = 10.06547855030069060m,
                            Name = "Labore quis voluptatem.",
                            Price = 10.9501842874801640m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=187"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Quis possimus dolorem quas rerum laudantium tenetur delectus voluptatibus non quasi dolor nemo praesentium est qui enim voluptatem dolorum hic.",
                            Discount = 10.5492717509853060m,
                            Name = "Perspiciatis ut eum.",
                            Price = 10.325572630076470m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=808"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Velit dolor ratione nulla voluptates dolore et ad omnis non aliquid neque minus molestiae dolorem ab et tempore in porro.",
                            Discount = 10.2236160059569480m,
                            Name = "Esse numquam laboriosam.",
                            Price = 10.5723281044384130m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=7"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Inventore qui facilis qui sunt qui consequuntur facere sit fugiat soluta nesciunt recusandae soluta sit hic autem a eos rerum.",
                            Discount = 10.4987478989636280m,
                            Name = "Est et voluptatem.",
                            Price = 10.5240934512224480m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=52"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Assumenda reiciendis corporis aspernatur quia doloribus non sunt qui magni reprehenderit quaerat et est tempore rerum eius natus sint facilis.",
                            Discount = 10.3883683166412490m,
                            Name = "Suscipit quo dolores.",
                            Price = 10.03705571453881250m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=942"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Autem natus quia omnis atque aliquam incidunt ex omnis aut id iste dolorem alias aut minus illum maiores optio molestiae.",
                            Discount = 10.8501755552600020m,
                            Name = "Sunt et aperiam.",
                            Price = 10.2783502318329880m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=114"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Praesentium vel cumque adipisci aut quaerat tenetur dolores aut consequuntur ex et consequatur velit magnam eveniet omnis deleniti consequatur ut.",
                            Discount = 10.9276658724656640m,
                            Name = "Nemo illum consectetur.",
                            Price = 10.6417086662918840m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=303"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Possimus rerum cumque quae rem libero veritatis est reiciendis architecto nobis qui exercitationem numquam accusamus aspernatur id praesentium vitae eligendi.",
                            Discount = 10.02674661531427250m,
                            Name = "Sed reprehenderit iusto.",
                            Price = 10.2271170817441850m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=498"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Unde provident quisquam et architecto et dolorem velit consectetur enim vitae aut labore earum molestiae ad dolorem architecto facere impedit.",
                            Discount = 10.7716372403184120m,
                            Name = "Quibusdam corporis rem.",
                            Price = 10.132797752568870m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=105"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Non qui asperiores id dolore ipsum adipisci sint labore aliquam fugiat est aut rem perferendis soluta temporibus occaecati culpa voluptas.",
                            Discount = 10.7986734266386710m,
                            Name = "Repellat eaque cumque.",
                            Price = 10.7497750365872750m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=57"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Laboriosam omnis cumque libero et aperiam repudiandae et totam adipisci nihil quo quo ipsa molestiae consectetur sit asperiores laudantium facilis.",
                            Discount = 10.1175255370873610m,
                            Name = "Voluptatem ipsa deserunt.",
                            Price = 10.2361786836926730m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=137"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Hic velit reiciendis et culpa sed in at id sed qui officia sunt velit vero perspiciatis atque vitae nobis et.",
                            Discount = 10.3221771779107760m,
                            Name = "Provident quam velit.",
                            Price = 10.7998278447426050m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=46"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Ex modi est distinctio eos dolorem quo sapiente sed quos sit quia harum eos amet eligendi et et ea necessitatibus.",
                            Discount = 10.3790180587112060m,
                            Name = "Dolores natus in.",
                            Price = 10.4457808325280350m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=797"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Qui et et et minus voluptatem et eius harum ab debitis ducimus voluptas minus ut et illo sequi sapiente ab.",
                            Discount = 10.6115497143992920m,
                            Name = "A pariatur omnis.",
                            Price = 10.7293328008285410m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=657"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Tenetur reiciendis est vitae cumque nostrum enim dignissimos suscipit ea magnam mollitia aut eum sint iste rerum omnis maiores quidem.",
                            Discount = 10.2123176568245130m,
                            Name = "Corporis minus tempore.",
                            Price = 10.153865368177120m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=1037"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Dolorem repellendus repellat nulla itaque alias aliquid nulla et voluptatibus ut quia nesciunt dolores nostrum eveniet dolore et iste eos.",
                            Discount = 10.8122466238272590m,
                            Name = "Qui repellat quibusdam.",
                            Price = 10.2205955820254030m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=562"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Sint maxime magnam magni et nihil dolores ducimus expedita suscipit natus enim mollitia facere maiores cum sunt tempore animi dolorem.",
                            Discount = 10.8613360998506360m,
                            Name = "Dolor voluptatem explicabo.",
                            Price = 10.1441102019250910m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=1074"
                        },
                        new
                        {
                            Id = 38,
                            Description = "In aut qui consequatur nam dolorum voluptates fugiat aut doloribus pariatur laboriosam rem nam quae quidem error est corrupti sapiente.",
                            Discount = 10.2361827233043420m,
                            Name = "Porro saepe eos.",
                            Price = 10.108236453080660m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=518"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Hic expedita et est esse id error sint iusto molestiae sit saepe est est et aut nobis quisquam sit magni.",
                            Discount = 10.09695433922901490m,
                            Name = "Voluptatem in quos.",
                            Price = 10.1631260836325240m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=524"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Doloremque laboriosam officiis dolore est dicta magni a quia tempore numquam iusto animi et maxime laborum impedit incidunt quibusdam quibusdam.",
                            Discount = 10.1879016962777370m,
                            Name = "Temporibus incidunt non.",
                            Price = 10.2728776951659830m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=814"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Voluptas at et soluta maiores sit aut sed culpa natus soluta rerum aut natus qui maxime quia totam veniam qui.",
                            Discount = 10.4188375945290730m,
                            Name = "Omnis maiores ducimus.",
                            Price = 10.2248756094951530m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=489"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Distinctio voluptas voluptatibus nihil atque cumque rerum aut odit maxime asperiores incidunt magnam quibusdam consequatur neque ab accusantium deserunt doloribus.",
                            Discount = 10.5436557617707440m,
                            Name = "Sint doloribus et.",
                            Price = 10.2384263864897310m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=561"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Modi voluptates consequatur repudiandae neque asperiores facere ratione eligendi mollitia dolores velit itaque dolorem possimus dolorum alias non labore aperiam.",
                            Discount = 10.8556824600583330m,
                            Name = "Voluptatibus voluptatum aliquam.",
                            Price = 10.9340387042304680m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=161"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Adipisci fugit in fugiat odio consequatur ducimus esse saepe quod eum fugiat labore et est tempore similique repudiandae eum et.",
                            Discount = 10.4822876003954040m,
                            Name = "Quos molestiae alias.",
                            Price = 10.82436314915510m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=470"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Quia consequatur et recusandae quam ut asperiores natus doloremque exercitationem omnis eligendi consectetur quos placeat eos aut ipsum vel alias.",
                            Discount = 10.283886613456480m,
                            Name = "Itaque maxime dignissimos.",
                            Price = 10.5336411034379350m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=478"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Dolor impedit adipisci a eveniet optio error consequuntur ab labore aut voluptate animi et itaque dolorum vel aut modi rerum.",
                            Discount = 10.07597833037189130m,
                            Name = "Sint nam ad.",
                            Price = 10.1596197956984960m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=746"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Voluptates eaque amet delectus esse possimus sapiente illum pariatur quo suscipit et repellat fuga consequatur optio dolorum architecto omnis omnis.",
                            Discount = 10.5954902589300140m,
                            Name = "Enim natus maxime.",
                            Price = 10.7555677032822590m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=43"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Fugit aut sunt sequi est laboriosam tenetur et dicta et ad reprehenderit et rerum molestiae dicta dolor ipsa earum modi.",
                            Discount = 10.7919964435473070m,
                            Name = "Aut exercitationem accusantium.",
                            Price = 10.01299157087364770m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=870"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Doloribus ipsam quis eum vitae sed minus nulla quo omnis nobis est cupiditate quae aut minima fugiat ut nobis aut.",
                            Discount = 10.3263529498718460m,
                            Name = "Delectus molestias dolor.",
                            Price = 10.1397751793916220m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=1084"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Aut quia quisquam sunt amet sit natus delectus laboriosam porro deleniti consectetur enim sint autem quo voluptas explicabo qui esse.",
                            Discount = 10.04027663592262040m,
                            Name = "Omnis earum architecto.",
                            Price = 10.1792029795140040m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=959"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Rerum distinctio consequatur corrupti fuga qui quae quisquam cupiditate asperiores libero dolores totam delectus beatae harum error aliquid sequi velit.",
                            Discount = 10.3470614828854150m,
                            Name = "Et veniam qui.",
                            Price = 10.1934269728108430m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=592"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Saepe ut consequatur dolor iusto et repellendus sint corporis provident tempora vero quae tempora adipisci enim quisquam expedita animi non.",
                            Discount = 10.09918526192157770m,
                            Name = "Temporibus commodi cupiditate.",
                            Price = 10.4508439374393060m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=195"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Sed exercitationem ab et cumque quaerat et voluptatem facere quo vel ut deserunt nobis quae omnis aut laboriosam quos odit.",
                            Discount = 10.9992359527383170m,
                            Name = "Adipisci dolores accusamus.",
                            Price = 10.1845749920162260m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=1027"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Architecto autem error et voluptatibus itaque aperiam culpa fuga magnam et cupiditate animi molestiae architecto dignissimos iste et nihil consequatur.",
                            Discount = 10.4033411249533950m,
                            Name = "Cupiditate consectetur iusto.",
                            Price = 10.2453226457561010m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=964"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Est sed numquam neque aut excepturi qui perspiciatis ex amet pariatur fugiat exercitationem natus aut nihil non velit vel saepe.",
                            Discount = 10.1097446620044040m,
                            Name = "Est cumque iure.",
                            Price = 10.6788819202589250m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=328"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Consectetur libero rem voluptatem aliquam minima omnis ut autem voluptate sunt et perferendis omnis rerum porro aliquam impedit architecto magni.",
                            Discount = 10.1422118177368360m,
                            Name = "Voluptatibus aspernatur sit.",
                            Price = 10.4473151529428150m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=566"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Impedit in est eligendi dolor alias voluptas et officiis aut molestiae deserunt omnis maxime non qui perferendis iusto in quibusdam.",
                            Discount = 10.7941882250803470m,
                            Name = "Aut autem consequatur.",
                            Price = 10.1137928213522740m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=862"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Id ab est cum nesciunt praesentium rem voluptas assumenda qui porro voluptates quibusdam nobis voluptatem aut fugiat sit fugit occaecati.",
                            Discount = 10.2350595738902030m,
                            Name = "Vel et ut.",
                            Price = 10.3854172478362070m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=327"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Optio sint amet ut debitis enim aperiam deserunt culpa amet sed voluptas magni vitae ut dignissimos alias ullam cupiditate id.",
                            Discount = 10.964003807382660m,
                            Name = "Ea cumque repellat.",
                            Price = 10.113875129313150m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=1049"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Qui et quidem quisquam voluptatem praesentium laudantium est molestiae qui vel quo quidem omnis sunt sunt dolorem et similique voluptatibus.",
                            Discount = 10.4827937085567010m,
                            Name = "Ut cumque iure.",
                            Price = 10.4372206611732120m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=604"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Aut minus magni et autem dolor rerum ducimus explicabo rerum laudantium rerum nemo nam nemo reiciendis vero dolorum praesentium rerum.",
                            Discount = 10.02253259300372220m,
                            Name = "Libero fugiat aspernatur.",
                            Price = 10.8417166182034260m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=448"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Hic aut impedit modi illo atque ea qui ipsa autem a consequatur distinctio facere ipsam repellat fuga commodi maxime voluptatem.",
                            Discount = 10.128223581299290m,
                            Name = "Molestiae ea porro.",
                            Price = 10.315551537235990m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=1040"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Aliquam eos laboriosam quia cumque aut praesentium itaque nisi iure quisquam velit in rerum vitae ut sit ut laborum et.",
                            Discount = 10.5256288393985610m,
                            Name = "Autem non rerum.",
                            Price = 10.1337730722193480m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=1013"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Ea qui mollitia est et nulla ut odit est nihil dolorum aliquam aperiam velit illum aut laborum et tenetur nisi.",
                            Discount = 10.2319496312327450m,
                            Name = "Mollitia sit qui.",
                            Price = 10.3165358092247210m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=832"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Vel qui fugiat sunt in sint eum inventore fugit maxime laborum nostrum similique eos voluptas ea natus error facilis culpa.",
                            Discount = 10.3164532651735720m,
                            Name = "Aperiam dolor voluptate.",
                            Price = 10.6021839858042930m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=348"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Dolorem ipsum a ad quod magnam iusto est autem necessitatibus dolores ipsa id sed qui nihil tempora repellat laborum iure.",
                            Discount = 10.4766084325856570m,
                            Name = "Eos facilis quo.",
                            Price = 10.4839656918700620m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=447"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Aut dolores dolor nihil impedit recusandae soluta consequatur rerum sequi totam officiis ipsa magni dolores laudantium rem molestiae occaecati voluptates.",
                            Discount = 10.4588748796185830m,
                            Name = "Possimus iure mollitia.",
                            Price = 10.3765562299529820m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=325"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Ex ut ullam distinctio occaecati ex et harum incidunt velit laudantium nihil aut inventore velit quaerat unde possimus consequuntur sunt.",
                            Discount = 10.3488673327252580m,
                            Name = "Velit dolore quaerat.",
                            Price = 10.255452916145070m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=354"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Modi ut aut pariatur aut praesentium tempore voluptas expedita qui dolores hic sint iure et et ut consequatur alias voluptate.",
                            Discount = 10.177217262413920m,
                            Name = "Officiis labore voluptatum.",
                            Price = 10.8510268143615810m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=434"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Alias consequatur suscipit eveniet repellendus veniam debitis et quis ut ut blanditiis delectus iusto minus perspiciatis tempore ab aut laborum.",
                            Discount = 10.7566518964044060m,
                            Name = "Sunt veniam tempore.",
                            Price = 10.1863352820213580m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=71"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Et quae ratione illum minima est repellendus tempore voluptatem voluptatem est impedit libero rerum a numquam natus sint omnis eaque.",
                            Discount = 10.1191966506276260m,
                            Name = "Qui accusamus eum.",
                            Price = 10.9728669999040980m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=808"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Corrupti dolore error deserunt quas sint blanditiis magnam iure eos non quasi qui dolor voluptas velit tempora maiores nisi eos.",
                            Discount = 10.2299060785350880m,
                            Name = "Perferendis voluptas tempore.",
                            Price = 10.970132082221160m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=573"
                        },
                        new
                        {
                            Id = 73,
                            Description = "At molestias velit et aut sint illo ullam nihil possimus est sit autem non reprehenderit similique architecto doloremque pariatur qui.",
                            Discount = 10.2080831104927150m,
                            Name = "Dolorem nulla fugiat.",
                            Price = 10.8610583063499340m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=957"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Cumque quaerat nihil soluta voluptas distinctio vitae animi quod aut cupiditate est omnis cum debitis laboriosam et et aut unde.",
                            Discount = 10.579013284099760m,
                            Name = "Perspiciatis tempore fuga.",
                            Price = 10.926886341966170m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=443"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Ut est et alias architecto dolores saepe aliquid ipsa quisquam beatae sapiente occaecati impedit laborum est deserunt omnis nemo exercitationem.",
                            Discount = 10.9829677720474860m,
                            Name = "Pariatur reiciendis voluptatem.",
                            Price = 10.1459347629667890m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=509"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Optio quia mollitia ut eum temporibus quidem fugit tenetur earum aut ducimus deserunt distinctio quia quo et in ut veniam.",
                            Discount = 10.3139813948953440m,
                            Name = "Voluptates quod quia.",
                            Price = 10.8391761173676590m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=59"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Debitis doloribus omnis maxime explicabo suscipit aut adipisci tempora dignissimos corrupti magnam quia aut mollitia distinctio nihil dolorum aut porro.",
                            Discount = 10.8212262163037560m,
                            Name = "Sint perspiciatis nobis.",
                            Price = 10.6337013038032230m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=71"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Veniam eum adipisci provident ipsam veniam odit omnis consequuntur quia velit aut fugit culpa totam aspernatur reprehenderit consequuntur quia consequatur.",
                            Discount = 10.2426582617883840m,
                            Name = "Deleniti quis blanditiis.",
                            Price = 10.3993027226064830m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=273"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Ab illo voluptas non voluptatem quisquam debitis qui vel aperiam voluptates quia delectus et quia rem atque molestias quod maiores.",
                            Discount = 10.1676369962131780m,
                            Name = "Dignissimos illum eum.",
                            Price = 10.1345337923311320m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=242"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Inventore ipsa qui ut dicta dolores blanditiis illo nihil veniam est recusandae nesciunt labore at et et atque tenetur ea.",
                            Discount = 10.2780036573661510m,
                            Name = "Quia sequi consequatur.",
                            Price = 10.2976047537744070m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=816"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Eligendi aut sit sunt ea odit porro illum est vitae veritatis dolorem soluta excepturi perferendis esse amet quo sunt qui.",
                            Discount = 10.2808535696383810m,
                            Name = "Porro nihil fugiat.",
                            Price = 10.7474854177550810m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=183"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Impedit dolor enim natus aliquam eum nam omnis quia autem adipisci dolore dolorem odio quam dolorem similique alias expedita ad.",
                            Discount = 10.2848370737791230m,
                            Name = "Enim ipsum quibusdam.",
                            Price = 10.8479602108001520m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=715"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Dicta velit consequatur tempore illum incidunt nemo aut eaque esse cupiditate consequatur odio perferendis placeat quo ipsa asperiores officia placeat.",
                            Discount = 10.327725228074810m,
                            Name = "Sit qui sed.",
                            Price = 10.1433788375665340m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=632"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Hic nihil sint nobis tempora aut ut culpa ut aut cumque autem perferendis sint et vel placeat quae consectetur eius.",
                            Discount = 10.09983164821743580m,
                            Name = "Expedita laborum eveniet.",
                            Price = 10.2594854227544210m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=1024"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Aut possimus ullam nihil perferendis quia suscipit ea officia quia minus ullam optio quia iusto in aperiam laboriosam et sunt.",
                            Discount = 10.7128968009319610m,
                            Name = "Officia maxime qui.",
                            Price = 10.2294630488517990m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=892"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Quidem pariatur reiciendis explicabo explicabo atque porro nostrum qui ab eum est ipsum soluta nesciunt voluptas quaerat sit placeat quos.",
                            Discount = 10.8239505439176920m,
                            Name = "Eveniet totam reprehenderit.",
                            Price = 10.0470165815423320m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=395"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Dolorem voluptatem consequatur recusandae cupiditate unde vel optio molestias laborum accusantium quidem vel reiciendis aut laborum ut est et dignissimos.",
                            Discount = 10.06979585255952360m,
                            Name = "Atque aut ipsum.",
                            Price = 10.8926951242111140m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=448"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Ut vel voluptatem error laborum quia ipsam omnis accusantium aut fugit vero eos ea maiores et incidunt ut eum recusandae.",
                            Discount = 10.1637916761281860m,
                            Name = "Ut voluptatem aut.",
                            Price = 10.5148289038403090m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=745"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Ad explicabo reprehenderit quia officia autem sunt totam rerum ex quae esse excepturi et molestiae vero animi ut autem excepturi.",
                            Discount = 10.9084927658124330m,
                            Name = "Voluptas eum non.",
                            Price = 10.08601284729596820m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=381"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Praesentium sit id quibusdam et dolor deserunt eaque praesentium harum necessitatibus non atque error saepe aut exercitationem amet illum accusamus.",
                            Discount = 10.08893009651868140m,
                            Name = "Qui delectus numquam.",
                            Price = 10.4336202803224420m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=691"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Dignissimos consequatur cum possimus libero dolorum nesciunt fugit quis minima natus dolore harum et laudantium delectus modi quo nihil enim.",
                            Discount = 10.1944147423815050m,
                            Name = "Sed ut voluptatem.",
                            Price = 10.9462282508361280m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=661"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Dolor consequatur officiis asperiores soluta eum praesentium voluptatem libero dolor debitis eius voluptates quia qui id qui id itaque sit.",
                            Discount = 10.969801669926290m,
                            Name = "Qui quidem aspernatur.",
                            Price = 10.9484977763837660m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=133"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Quis dolore natus iste corporis aperiam cupiditate vel maxime velit quis debitis esse quia assumenda quibusdam amet ut dolores quibusdam.",
                            Discount = 10.4961576869227730m,
                            Name = "Eveniet velit distinctio.",
                            Price = 10.9869944909526940m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=91"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Voluptatem vel dolore temporibus aspernatur ut ipsum sunt ut odit tempora sunt sit eum rerum nihil adipisci provident vero cupiditate.",
                            Discount = 10.1799076777789310m,
                            Name = "Iure excepturi qui.",
                            Price = 10.01135355327807070m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=1072"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Tempore debitis distinctio sunt dolorem autem qui autem error et dolorum consectetur est dolore vitae et est sapiente est enim.",
                            Discount = 10.04164590967895740m,
                            Name = "Id in et.",
                            Price = 10.4111543388157870m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=1013"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Odio ut quidem ipsam ab optio et dolores non et sed inventore omnis animi aut vel quia sunt laboriosam magnam.",
                            Discount = 10.9270845907400760m,
                            Name = "Blanditiis non doloribus.",
                            Price = 10.2756533200273540m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=426"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Quia harum dicta ut fugit rerum aut qui ea molestiae sit similique dolores a facere officiis fuga voluptatem ut asperiores.",
                            Discount = 10.3999534367583480m,
                            Name = "Aut delectus sunt.",
                            Price = 10.7107035898187680m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=528"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Quo excepturi expedita voluptatem laboriosam dicta id dignissimos eos consequuntur reiciendis quam esse aut blanditiis est qui voluptatem consequatur nulla.",
                            Discount = 10.5232886097036720m,
                            Name = "Qui fugit ad.",
                            Price = 10.2923071204183190m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=636"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Vel aut ut dolores ducimus repellat commodi sunt harum placeat omnis nulla deleniti necessitatibus excepturi necessitatibus maxime facilis qui corrupti.",
                            Discount = 10.2540876820004020m,
                            Name = "Suscipit quasi ut.",
                            Price = 10.02099296451592490m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=750"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Maiores consectetur praesentium sapiente vel enim sed tempora rerum saepe et non nihil ab aut dolorem vero cum dolor cupiditate.",
                            Discount = 10.780064592966840m,
                            Name = "Error vel enim.",
                            Price = 10.9556769486310320m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=226"
                        });
                });

            modelBuilder.Entity("IntroSEProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IntroSEProject.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("IntroSEProject.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("IntroSEProject.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("IntroSEProject.Models.SeatReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("SeatReservation");
                });

            modelBuilder.Entity("IntroSEProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailConfirmToken")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/753.jpg",
                            DateOfBirth = new DateTime(2023, 1, 30, 11, 45, 17, 856, DateTimeKind.Local).AddTicks(2753),
                            Email = "ClarkFadel.Stark@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Clark Fadel",
                            Gender = "Female",
                            Password = "DZBRHDGI6q",
                            PhoneNumber = "1-889-737-9865 x33749",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/76.jpg",
                            DateOfBirth = new DateTime(2023, 3, 20, 0, 30, 28, 316, DateTimeKind.Local).AddTicks(7012),
                            Email = "BethNicolas17@hotmail.com",
                            EmailConfirmed = false,
                            FullName = "Beth Nicolas",
                            Gender = "Female",
                            Password = "7JyPeJbP8k",
                            PhoneNumber = "1-666-934-7051 x29752",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/789.jpg",
                            DateOfBirth = new DateTime(2023, 2, 15, 21, 23, 56, 966, DateTimeKind.Local).AddTicks(5950),
                            Email = "AylaEbert74@hotmail.com",
                            EmailConfirmed = false,
                            FullName = "Ayla Ebert",
                            Gender = "Female",
                            Password = "FGtKv09y4J",
                            PhoneNumber = "(663) 951-5830 x4872",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/947.jpg",
                            DateOfBirth = new DateTime(2023, 7, 25, 0, 39, 45, 883, DateTimeKind.Local).AddTicks(632),
                            Email = "EstevanBogisich.Skiles@yahoo.com",
                            EmailConfirmed = false,
                            FullName = "Estevan Bogisich",
                            Gender = "Female",
                            Password = "yNeq0uPIe4",
                            PhoneNumber = "1-713-316-9030",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1062.jpg",
                            DateOfBirth = new DateTime(2023, 1, 27, 15, 20, 42, 626, DateTimeKind.Local).AddTicks(9072),
                            Email = "PhilipPollich_Terry@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Philip Pollich",
                            Gender = "Male",
                            Password = "GR7yOwso6s",
                            PhoneNumber = "317.752.1611 x9359",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/49.jpg",
                            DateOfBirth = new DateTime(2023, 10, 31, 19, 28, 2, 531, DateTimeKind.Local).AddTicks(7986),
                            Email = "LibbieHeathcote.Bins14@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Libbie Heathcote",
                            Gender = "Male",
                            Password = "o4vdUhkpIn",
                            PhoneNumber = "319.502.8272 x48793",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1020.jpg",
                            DateOfBirth = new DateTime(2023, 11, 26, 14, 45, 11, 851, DateTimeKind.Local).AddTicks(2976),
                            Email = "HildaGraham.Balistreri6@hotmail.com",
                            EmailConfirmed = false,
                            FullName = "Hilda Graham",
                            Gender = "Male",
                            Password = "1zF6OQAGJL",
                            PhoneNumber = "597-752-7924 x0122",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/109.jpg",
                            DateOfBirth = new DateTime(2023, 6, 3, 20, 50, 49, 855, DateTimeKind.Local).AddTicks(5294),
                            Email = "EulaliaBartell87@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Eulalia Bartell",
                            Gender = "Male",
                            Password = "_nP5wBstle",
                            PhoneNumber = "(315) 869-1332 x0488",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/88.jpg",
                            DateOfBirth = new DateTime(2023, 3, 24, 11, 3, 5, 418, DateTimeKind.Local).AddTicks(2456),
                            Email = "PaoloMcCullough.Weimann17@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Paolo McCullough",
                            Gender = "Female",
                            Password = "I7RR7JTvse",
                            PhoneNumber = "541-747-8384",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1170.jpg",
                            DateOfBirth = new DateTime(2023, 10, 15, 21, 14, 31, 670, DateTimeKind.Local).AddTicks(7087),
                            Email = "AndreaneBogisich_Hintz@hotmail.com",
                            EmailConfirmed = false,
                            FullName = "Andreane Bogisich",
                            Gender = "Male",
                            Password = "SFATDQgzLK",
                            PhoneNumber = "238-766-1993",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("IntroSEProject.Models.CartItem", b =>
                {
                    b.HasOne("IntroSEProject.Models.Item", "Item")
                        .WithMany("CartItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntroSEProject.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntroSEProject.Models.Item", b =>
                {
                    b.HasOne("IntroSEProject.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IntroSEProject.Models.Order", b =>
                {
                    b.HasOne("IntroSEProject.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntroSEProject.Models.OrderItem", b =>
                {
                    b.HasOne("IntroSEProject.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntroSEProject.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IntroSEProject.Models.Payment", b =>
                {
                    b.HasOne("IntroSEProject.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntroSEProject.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntroSEProject.Models.Review", b =>
                {
                    b.HasOne("IntroSEProject.Models.OrderItem", "OrderItem")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntroSEProject.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntroSEProject.Models.SeatReservation", b =>
                {
                    b.HasOne("IntroSEProject.Models.Order", "Order")
                        .WithMany("SeatReservations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IntroSEProject.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IntroSEProject.Models.Item", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("IntroSEProject.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("SeatReservations");
                });

            modelBuilder.Entity("IntroSEProject.Models.OrderItem", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("IntroSEProject.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
