// <auto-generated />
using System;
using IntroSEProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IntroSEProject.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("IntroSEProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hic provident voluptate et occaecati aperiam placeat sapiente. Quas aut non quae voluptas ratione voluptas impedit similique ut.",
                            Name = "Autem commodi qui.",
                            Thumbnail = "https://picsum.photos/640/480/?image=233"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dolores mollitia distinctio adipisci ad doloribus minus corporis occaecati. Perferendis in et est ut. Iste temporibus ducimus nam omnis. Eligendi quia rerum libero quibusdam magni velit et id eos.",
                            Name = "Qui numquam qui.",
                            Thumbnail = "https://picsum.photos/640/480/?image=134"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nobis sint quasi tempora cupiditate velit magni placeat repellendus.",
                            Name = "Ducimus accusantium odio.",
                            Thumbnail = "https://picsum.photos/640/480/?image=597"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Adipisci eaque dolores et blanditiis nemo est adipisci id odit. Dolorum debitis accusantium voluptatum culpa.",
                            Name = "Sint accusamus voluptas.",
                            Thumbnail = "https://picsum.photos/640/480/?image=1042"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Provident voluptatum veniam architecto eos aut quo. Voluptas in enim consectetur. Velit non sed harum praesentium. Voluptatem totam quia.",
                            Name = "Dolorem temporibus odit.",
                            Thumbnail = "https://picsum.photos/640/480/?image=986"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Aut nihil illo voluptatem sit id. Voluptatem dolorum vel ipsum qui ex reprehenderit.",
                            Name = "Temporibus aliquam est.",
                            Thumbnail = "https://picsum.photos/640/480/?image=263"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Illo quis provident. Doloremque laborum quia velit incidunt. Qui esse similique blanditiis sed dolorum.",
                            Name = "Debitis enim nobis.",
                            Thumbnail = "https://picsum.photos/640/480/?image=843"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Repudiandae aliquam nostrum ut sapiente architecto nisi. Deleniti similique illo magnam quia. Quia est nostrum voluptate deleniti sunt temporibus magni. Possimus nesciunt ut consectetur sequi provident voluptatem.",
                            Name = "Doloribus quia facere.",
                            Thumbnail = "https://picsum.photos/640/480/?image=378"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Eaque nobis est ab quasi. Perferendis aliquam ea voluptatem magni similique ducimus dolorum cumque.",
                            Name = "Sint sequi unde.",
                            Thumbnail = "https://picsum.photos/640/480/?image=555"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Provident amet veritatis rerum amet fugiat nesciunt illo. Explicabo omnis quia saepe. Id omnis et voluptatem et fugit ullam qui. Assumenda fuga impedit voluptates dolorum maxime facilis suscipit fugiat.",
                            Name = "Ad illum porro.",
                            Thumbnail = "https://picsum.photos/640/480/?image=832"
                        });
                });

            modelBuilder.Entity("IntroSEProject.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Images")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 10,
                            Description = "Neque aut aperiam at sed modi modi ex reprehenderit omnis recusandae explicabo consequatur voluptas quibusdam autem libero qui eos ut.",
                            Discount = 10.2625183897384060m,
                            Name = "Quas dolores qui.",
                            Price = 10.2963503856660570m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=630"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Rerum et ipsam amet aut dolor ut qui necessitatibus quaerat aspernatur quia et velit incidunt sequi aut non id et.",
                            Discount = 10.03798936216067030m,
                            Name = "Enim dolores possimus.",
                            Price = 10.5412858498940640m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=581"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "In odit voluptatem necessitatibus qui laudantium velit necessitatibus labore maxime voluptatibus eum in et et voluptate exercitationem delectus qui rerum.",
                            Discount = 10.326636820252350m,
                            Name = "Voluptatem quis ut.",
                            Price = 10.03043520032914130m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=396"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Description = "Dolores magni qui sapiente necessitatibus consequatur maxime dolor earum non dignissimos voluptatem alias nisi sint tempora unde et modi necessitatibus.",
                            Discount = 10.5966029826535860m,
                            Name = "Eligendi eius et.",
                            Price = 10.132526158882550m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=621"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            Description = "Nesciunt enim voluptatem aperiam dolore quas reprehenderit odit molestiae voluptatem earum non voluptates consequuntur totam dicta occaecati in aut est.",
                            Discount = 10.7227451758099460m,
                            Name = "Ea accusamus architecto.",
                            Price = 10.4103319758597440m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=454"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 9,
                            Description = "Et quam ut corrupti dolores tempore fuga et necessitatibus velit et et hic consequatur corporis cupiditate delectus perferendis reiciendis consequatur.",
                            Discount = 10.8010868797083790m,
                            Name = "Voluptas est ut.",
                            Price = 10.1289434875962060m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=510"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Description = "At et error sint qui quos et quas deleniti qui quo labore quas quo adipisci aut tempore eum id animi.",
                            Discount = 10.9365007402079650m,
                            Name = "Sit distinctio iusto.",
                            Price = 10.4204837742356970m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=564"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Ut cumque ut enim aut amet omnis labore nulla maiores est praesentium earum quibusdam ipsa excepturi corporis quod quas nostrum.",
                            Discount = 10.7718144747297350m,
                            Name = "Assumenda assumenda odio.",
                            Price = 10.6045905405676880m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=379"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            Description = "Hic odit similique sapiente quisquam nihil delectus dolor atque in incidunt ipsam veritatis a voluptatem est laborum minima expedita fuga.",
                            Discount = 10.1906744773456240m,
                            Name = "Veritatis perferendis sint.",
                            Price = 10.8944052471287570m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=485"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Provident eum et hic quia eos nostrum quod quam consequatur id occaecati eum quaerat accusantium ut molestias consectetur tempora est.",
                            Discount = 10.4805595807174960m,
                            Name = "Deleniti quo voluptas.",
                            Price = 10.5097492139366220m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=285"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Tenetur a optio labore officia velit dolore et provident veniam qui sed nam cupiditate ut et ut eos autem harum.",
                            Discount = 10.2493246203518120m,
                            Name = "Reprehenderit voluptatem possimus.",
                            Price = 10.1639356581326270m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=436"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Corporis optio perspiciatis repellendus quo provident repellendus praesentium fugit dolores non et aut quis quis tempora ab voluptatem voluptatibus maiores.",
                            Discount = 10.7247175256371110m,
                            Name = "Amet quaerat ab.",
                            Price = 10.2123786831332270m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=276"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Vero fuga maiores in earum velit ut quo id ex commodi dolores quod consequatur est ipsa non dolorem dolorum autem.",
                            Discount = 10.8723146411927020m,
                            Name = "Iure deserunt nihil.",
                            Price = 10.8797984127326860m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=645"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Et veniam amet qui itaque beatae id quos excepturi provident nobis vel voluptatem provident quos eligendi expedita pariatur dolore ea.",
                            Discount = 10.5879134822580560m,
                            Name = "Enim voluptas culpa.",
                            Price = 10.03760047724358760m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=224"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Animi facere consectetur tempore ex assumenda est qui dolorem repudiandae adipisci distinctio sed velit non cum deleniti consequatur assumenda ut.",
                            Discount = 10.3335734658565250m,
                            Name = "Et dolorem maiores.",
                            Price = 10.3806697308927170m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=830"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 10,
                            Description = "Incidunt omnis nobis eos magnam et saepe omnis laboriosam perferendis blanditiis aliquam omnis eaque cupiditate quod expedita qui velit voluptas.",
                            Discount = 10.3747270220772950m,
                            Name = "Iusto perspiciatis deleniti.",
                            Price = 10.05880133624132780m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=24"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Dolor fugiat est et tempora exercitationem modi voluptate incidunt inventore velit officia corporis assumenda laboriosam totam aliquid sint officia laboriosam.",
                            Discount = 10.8324844869004960m,
                            Name = "Deleniti id voluptatem.",
                            Price = 10.8106078183327840m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=36"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Description = "Consequatur qui aut est perferendis et qui quas commodi sed doloremque totam illum fugit excepturi animi quia laborum sed nostrum.",
                            Discount = 10.4820664923088940m,
                            Name = "Cumque quam vero.",
                            Price = 10.03532572883894930m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=254"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            Description = "Dolores non est cupiditate officiis commodi mollitia quas tenetur rerum in cum sit quo aut vel corrupti quia cupiditate optio.",
                            Discount = 10.1029057507882390m,
                            Name = "Voluptatem blanditiis nisi.",
                            Price = 10.3191942983861990m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=966"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            Description = "Sed qui aut placeat ipsum labore quis voluptatem pariatur quas deserunt blanditiis sint aut facilis sed eaque vero odit velit.",
                            Discount = 10.7935940780647070m,
                            Name = "Magni qui voluptas.",
                            Price = 10.3786912906815720m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=180"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Hic et ex maxime perspiciatis ut eum quis possimus dolorem quas rerum laudantium tenetur delectus voluptatibus non quasi dolor nemo.",
                            Discount = 10.7265682815232160m,
                            Name = "Possimus accusantium doloremque.",
                            Price = 10.4579704527081780m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=804"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            Description = "Unde aut consequatur esse numquam laboriosam velit dolor ratione nulla voluptates dolore et ad omnis non aliquid neque minus molestiae.",
                            Discount = 10.05215638226464220m,
                            Name = "Dolorum hic voluptas.",
                            Price = 10.8268247311128420m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=23"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 9,
                            Description = "Deleniti quae est et voluptatem inventore qui facilis qui sunt qui consequuntur facere sit fugiat soluta nesciunt recusandae soluta sit.",
                            Discount = 10.3750201940420180m,
                            Name = "Porro sunt modi.",
                            Price = 10.9479698091503090m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=627"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            Description = "Accusamus suscipit quo dolores assumenda reiciendis corporis aspernatur quia doloribus non sunt qui magni reprehenderit quaerat et est tempore rerum.",
                            Discount = 10.5617888674893360m,
                            Name = "Cupiditate et dolores.",
                            Price = 10.2174593523226020m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=962"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Sunt et aperiam autem natus quia omnis atque aliquam incidunt ex omnis aut id iste dolorem alias aut minus illum.",
                            Discount = 10.6974806183471720m,
                            Name = "Iure ad odit.",
                            Price = 10.9849612307664760m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=40"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 10,
                            Description = "Illum consectetur praesentium vel cumque adipisci aut quaerat tenetur dolores aut consequuntur ex et consequatur velit magnam eveniet omnis deleniti.",
                            Discount = 10.3466915401381870m,
                            Name = "Vero minima nemo.",
                            Price = 10.004965144211875810m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=922"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 10,
                            Description = "Iusto possimus rerum cumque quae rem libero veritatis est reiciendis architecto nobis qui exercitationem numquam accusamus aspernatur id praesentium vitae.",
                            Discount = 10.2271170817441850m,
                            Name = "Praesentium sed reprehenderit.",
                            Price = 10.6917929256762340m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=712"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            Description = "Unde provident quisquam et architecto et dolorem velit consectetur enim vitae aut labore earum molestiae ad dolorem architecto facere impedit.",
                            Discount = 10.7716372403184120m,
                            Name = "Quibusdam corporis rem.",
                            Price = 10.132797752568870m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=105"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            Description = "Qui asperiores id dolore ipsum adipisci sint labore aliquam fugiat est aut rem perferendis soluta temporibus occaecati culpa voluptas placeat.",
                            Discount = 10.7531153786709140m,
                            Name = "Eaque cumque non.",
                            Price = 10.7986734266386710m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=1082"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            Description = "Cumque libero et aperiam repudiandae et totam adipisci nihil quo quo ipsa molestiae consectetur sit asperiores laudantium facilis ut sed.",
                            Discount = 10.0424019196268180m,
                            Name = "Deserunt laboriosam omnis.",
                            Price = 10.09077552710230250m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=47"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            Description = "Et culpa sed in at id sed qui officia sunt velit vero perspiciatis atque vitae nobis et et quia est.",
                            Discount = 10.1343380595251630m,
                            Name = "Hic velit reiciendis.",
                            Price = 10.7347888512233220m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=213"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Description = "Eos dolorem quo sapiente sed quos sit quia harum eos amet eligendi et et ea necessitatibus dignissimos vel sunt id.",
                            Discount = 10.8474100436304740m,
                            Name = "Modi est distinctio.",
                            Price = 10.9588632378535640m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=387"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 10,
                            Description = "Voluptatem et eius harum ab debitis ducimus voluptas minus ut et illo sequi sapiente ab qui laborum harum a corporis.",
                            Discount = 10.6718539049252190m,
                            Name = "Et et minus.",
                            Price = 10.7311544002644510m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=682"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 10,
                            Description = "Enim dignissimos suscipit ea magnam mollitia aut eum sint iste rerum omnis maiores quidem sequi non est occaecati qui repellat.",
                            Discount = 10.8239445834532120m,
                            Name = "Vitae cumque nostrum.",
                            Price = 10.7957327523248890m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=705"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Description = "Nulla et voluptatibus ut quia nesciunt dolores nostrum eveniet dolore et iste eos eius vel illo doloribus dolor voluptatem explicabo.",
                            Discount = 10.7429860605592770m,
                            Name = "Itaque alias aliquid.",
                            Price = 10.5179885367480980m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=916"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 7,
                            Description = "Expedita suscipit natus enim mollitia facere maiores cum sunt tempore animi dolorem qui eos enim voluptatum porro saepe eos in.",
                            Discount = 10.7292284470653290m,
                            Name = "Nihil dolores ducimus.",
                            Price = 10.01169795962595290m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=683"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            Description = "Doloribus pariatur laboriosam rem nam quae quidem error est corrupti sapiente odit ut eos atque voluptatem in quos hic expedita.",
                            Discount = 10.7734644444535790m,
                            Name = "Voluptates fugiat aut.",
                            Price = 10.4297642737765630m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=674"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Description = "Sit saepe est est et aut nobis quisquam sit magni neque aspernatur tempora placeat temporibus incidunt non doloremque laboriosam officiis.",
                            Discount = 10.6882577537038630m,
                            Name = "Sint iusto molestiae.",
                            Price = 10.2458523671356270m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=613"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 6,
                            Description = "Iusto animi et maxime laborum impedit incidunt quibusdam quibusdam enim amet ex qui omnis maiores ducimus voluptas at et soluta.",
                            Discount = 10.1846909831206740m,
                            Name = "Quia tempore numquam.",
                            Price = 10.9854659703492490m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=1040"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            Description = "Aut natus qui maxime quia totam veniam qui modi quam atque sint sint doloribus et distinctio voluptas voluptatibus nihil atque.",
                            Discount = 10.6400921240635640m,
                            Name = "Natus soluta rerum.",
                            Price = 10.7020601731268970m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=629"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 6,
                            Description = "Quibusdam consequatur neque ab accusantium deserunt doloribus labore perspiciatis dignissimos voluptatem voluptatibus voluptatum aliquam modi voluptates consequatur repudiandae neque asperiores.",
                            Discount = 10.1464930410247730m,
                            Name = "Asperiores incidunt magnam.",
                            Price = 10.7534902155182740m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=807"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 9,
                            Description = "Possimus dolorum alias non labore aperiam recusandae vero aliquam et quos molestiae alias adipisci fugit in fugiat odio consequatur ducimus.",
                            Discount = 10.8945869006656980m,
                            Name = "Velit itaque dolorem.",
                            Price = 10.4175728752359620m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=147"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 7,
                            Description = "Tempore similique repudiandae eum et dolorem atque et odio itaque maxime dignissimos quia consequatur et recusandae quam ut asperiores natus.",
                            Discount = 10.2954446791184340m,
                            Name = "Labore et est.",
                            Price = 10.03130551475626670m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=904"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 6,
                            Description = "Aut ipsum vel alias provident veniam sit est sint nam ad dolor impedit adipisci a eveniet optio error consequuntur ab.",
                            Discount = 10.8069246317292210m,
                            Name = "Quos placeat eos.",
                            Price = 10.240623686574690m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=205"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 7,
                            Description = "Aut modi rerum nesciunt architecto dolorum ipsa enim natus maxime voluptates eaque amet delectus esse possimus sapiente illum pariatur quo.",
                            Discount = 10.8638733322098260m,
                            Name = "Itaque dolorum vel.",
                            Price = 10.3367561368908530m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=265"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Description = "Omnis omnis possimus mollitia nam et aut exercitationem accusantium fugit aut sunt sequi est laboriosam tenetur et dicta et ad.",
                            Discount = 10.6511356912791430m,
                            Name = "Optio dolorum architecto.",
                            Price = 10.39117304160780m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=398"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 3,
                            Description = "Modi perferendis autem vel repellat delectus molestias dolor doloribus ipsam quis eum vitae sed minus nulla quo omnis nobis est.",
                            Discount = 10.04439474784042440m,
                            Name = "Dolor ipsa earum.",
                            Price = 10.5246896997674790m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=95"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Description = "Eos voluptas molestias rerum omnis earum architecto aut quia quisquam sunt amet sit natus delectus laboriosam porro deleniti consectetur enim.",
                            Discount = 10.7927136965062070m,
                            Name = "Ut nobis aut.",
                            Price = 10.9170733103142460m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=903"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Description = "Ipsa excepturi perspiciatis et veniam qui rerum distinctio consequatur corrupti fuga qui quae quisquam cupiditate asperiores libero dolores totam delectus.",
                            Discount = 10.6344256757918860m,
                            Name = "Qui esse dolor.",
                            Price = 10.08001771759242640m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=104"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 6,
                            Description = "Laborum dolor temporibus commodi cupiditate saepe ut consequatur dolor iusto et repellendus sint corporis provident tempora vero quae tempora adipisci.",
                            Discount = 10.7226068911713580m,
                            Name = "Velit adipisci ut.",
                            Price = 10.2690955853411440m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=169"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            Description = "Rerum adipisci dolores accusamus sed exercitationem ab et cumque quaerat et voluptatem facere quo vel ut deserunt nobis quae omnis.",
                            Discount = 10.3387600008113120m,
                            Name = "Qui aspernatur voluptate.",
                            Price = 10.1035276526135990m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=1007"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 3,
                            Description = "Cupiditate consectetur iusto architecto autem error et voluptatibus itaque aperiam culpa fuga magnam et cupiditate animi molestiae architecto dignissimos iste.",
                            Discount = 10.4230986537519370m,
                            Name = "Repellat beatae necessitatibus.",
                            Price = 10.9074631416739260m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=200"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            Description = "Cumque iure est sed numquam neque aut excepturi qui perspiciatis ex amet pariatur fugiat exercitationem natus aut nihil non velit.",
                            Discount = 10.8927331985406260m,
                            Name = "Quia corporis est.",
                            Price = 10.8129870825507620m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=437"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 10,
                            Description = "Sit consectetur libero rem voluptatem aliquam minima omnis ut autem voluptate sunt et perferendis omnis rerum porro aliquam impedit architecto.",
                            Discount = 10.4473151529428150m,
                            Name = "Occaecati voluptatibus aspernatur.",
                            Price = 10.1288737422455450m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=604"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 4,
                            Description = "Impedit in est eligendi dolor alias voluptas et officiis aut molestiae deserunt omnis maxime non qui perferendis iusto in quibusdam.",
                            Discount = 10.7941882250803470m,
                            Name = "Aut autem consequatur.",
                            Price = 10.1137928213522740m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=862"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 4,
                            Description = "Ab est cum nesciunt praesentium rem voluptas assumenda qui porro voluptates quibusdam nobis voluptatem aut fugiat sit fugit occaecati eum.",
                            Discount = 10.4139979129722330m,
                            Name = "Et ut id.",
                            Price = 10.2350595738902030m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=884"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            Description = "Amet ut debitis enim aperiam deserunt culpa amet sed voluptas magni vitae ut dignissimos alias ullam cupiditate id fugit delectus.",
                            Discount = 10.5571355826953130m,
                            Name = "Repellat optio sint.",
                            Price = 10.784002793386580m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=761"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 1,
                            Description = "Quisquam voluptatem praesentium laudantium est molestiae qui vel quo quidem omnis sunt sunt dolorem et similique voluptatibus iusto atque autem.",
                            Discount = 10.6696907135982490m,
                            Name = "Qui et quidem.",
                            Price = 10.4129186297827020m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=419"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 10,
                            Description = "Autem dolor rerum ducimus explicabo rerum laudantium rerum nemo nam nemo reiciendis vero dolorum praesentium rerum voluptas voluptatem qui a.",
                            Discount = 10.403455617559820m,
                            Name = "Minus magni et.",
                            Price = 10.9273080499504260m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=957"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 9,
                            Description = "Atque ea qui ipsa autem a consequatur distinctio facere ipsam repellat fuga commodi maxime voluptatem ipsam consequuntur quas recusandae autem.",
                            Discount = 10.946874153775570m,
                            Name = "Impedit modi illo.",
                            Price = 10.2089539362159340m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=111"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 6,
                            Description = "Praesentium itaque nisi iure quisquam velit in rerum vitae ut sit ut laborum et dolores cupiditate accusantium assumenda mollitia sit.",
                            Discount = 10.4030582892722720m,
                            Name = "Quia cumque aut.",
                            Price = 10.1419660845501190m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=366"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 6,
                            Description = "Odit est nihil dolorum aliquam aperiam velit illum aut laborum et tenetur nisi ipsam incidunt eos voluptatem aperiam dolor voluptate.",
                            Discount = 10.7300951731065730m,
                            Name = "Et nulla ut.",
                            Price = 10.8131010815562220m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=839"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 8,
                            Description = "Fugit maxime laborum nostrum similique eos voluptas ea natus error facilis culpa animi ipsam omnis velit eos facilis quo dolorem.",
                            Discount = 10.959430305268350m,
                            Name = "Sint eum inventore.",
                            Price = 10.1711086580395270m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=625"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 10,
                            Description = "Necessitatibus dolores ipsa id sed qui nihil tempora repellat laborum iure atque voluptatum officiis ullam possimus iure mollitia aut dolores.",
                            Discount = 10.4226773182967110m,
                            Name = "Iusto est autem.",
                            Price = 10.1767199990231170m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=272"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            Description = "Totam officiis ipsa magni dolores laudantium rem molestiae occaecati voluptates autem praesentium laborum voluptas velit dolore quaerat ex ut ullam.",
                            Discount = 10.519489905573190m,
                            Name = "Consequatur rerum sequi.",
                            Price = 10.6590580174974440m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=737"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 4,
                            Description = "Nihil aut inventore velit quaerat unde possimus consequuntur sunt aliquam ut aut in officiis labore voluptatum modi ut aut pariatur.",
                            Discount = 10.4609699395769140m,
                            Name = "Incidunt velit laudantium.",
                            Price = 10.01036988152673930m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=685"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 3,
                            Description = "Sint iure et et ut consequatur alias voluptate pariatur dolor velit et sunt veniam tempore alias consequatur suscipit eveniet repellendus.",
                            Discount = 10.8764901779948220m,
                            Name = "Qui dolores hic.",
                            Price = 10.2824465927120520m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=711"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 4,
                            Description = "Iusto minus perspiciatis tempore ab aut laborum amet possimus dignissimos maxime qui accusamus eum et quae ratione illum minima est.",
                            Discount = 10.6716389910651550m,
                            Name = "Ut blanditiis delectus.",
                            Price = 10.786900898342440m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=375"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 6,
                            Description = "A numquam natus sint omnis eaque aut sed harum non perferendis voluptas tempore corrupti dolore error deserunt quas sint blanditiis.",
                            Discount = 10.38651089015720m,
                            Name = "Impedit libero rerum.",
                            Price = 10.2497615386963640m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=745"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 2,
                            Description = "Velit tempora maiores nisi eos ut incidunt perspiciatis aut dolorem nulla fugiat at molestias velit et aut sint illo ullam.",
                            Discount = 10.7582301240219880m,
                            Name = "Qui dolor voluptas.",
                            Price = 10.425459138315850m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=75"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 6,
                            Description = "Architecto doloremque pariatur qui eos quia impedit voluptate perspiciatis tempore fuga cumque quaerat nihil soluta voluptas distinctio vitae animi quod.",
                            Discount = 10.5231073622233730m,
                            Name = "Non reprehenderit similique.",
                            Price = 10.9755667117310530m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=861"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 8,
                            Description = "Et aut unde molestiae culpa distinctio totam pariatur reiciendis voluptatem ut est et alias architecto dolores saepe aliquid ipsa quisquam.",
                            Discount = 10.9604398021290260m,
                            Name = "Debitis laboriosam et.",
                            Price = 10.078668647016710m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=732"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 4,
                            Description = "Nemo exercitationem ratione voluptatibus accusamus illo voluptates quod quia optio quia mollitia ut eum temporibus quidem fugit tenetur earum aut.",
                            Discount = 10.5915799460334610m,
                            Name = "Est deserunt omnis.",
                            Price = 10.4493315738855540m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=665"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 7,
                            Description = "Veniam quo ipsam non et sint perspiciatis nobis debitis doloribus omnis maxime explicabo suscipit aut adipisci tempora dignissimos corrupti magnam.",
                            Discount = 10.8829374871602920m,
                            Name = "Et in ut.",
                            Price = 10.1728245085910080m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=907"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 4,
                            Description = "Harum qui ratione magnam deleniti quis blanditiis veniam eum adipisci provident ipsam veniam odit omnis consequuntur quia velit aut fugit.",
                            Discount = 10.4660643075900450m,
                            Name = "Dolorum aut porro.",
                            Price = 10.5810501950704730m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=766"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 6,
                            Description = "Et et modi dignissimos illum eum ab illo voluptas non voluptatem quisquam debitis qui vel aperiam voluptates quia delectus et.",
                            Discount = 10.4713754320849550m,
                            Name = "Quia consequatur in.",
                            Price = 10.1212990652403320m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=138"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 10,
                            Description = "Est facere quia sequi consequatur inventore ipsa qui ut dicta dolores blanditiis illo nihil veniam est recusandae nesciunt labore at.",
                            Discount = 10.06437807719427070m,
                            Name = "Maiores dolores dolorem.",
                            Price = 10.6535907455969560m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=804"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 6,
                            Description = "Ipsum porro nihil fugiat eligendi aut sit sunt ea odit porro illum est vitae veritatis dolorem soluta excepturi perferendis esse.",
                            Discount = 10.8361547439527490m,
                            Name = "Ullam minima est.",
                            Price = 10.1879689275231070m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=388"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 9,
                            Description = "Enim ipsum quibusdam impedit dolor enim natus aliquam eum nam omnis quia autem adipisci dolore dolorem odio quam dolorem similique.",
                            Discount = 10.658522922852320m,
                            Name = "Minima excepturi distinctio.",
                            Price = 10.0007793833505266270m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=811"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 4,
                            Description = "Qui sed dicta velit consequatur tempore illum incidunt nemo aut eaque esse cupiditate consequatur odio perferendis placeat quo ipsa asperiores.",
                            Discount = 10.747361284563020m,
                            Name = "Eos qui sit.",
                            Price = 10.5894991953808340m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=309"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 5,
                            Description = "Eveniet hic nihil sint nobis tempora aut ut culpa ut aut cumque autem perferendis sint et vel placeat quae consectetur.",
                            Discount = 10.2594854227544210m,
                            Name = "Rerum expedita laborum.",
                            Price = 10.2199649062100630m,
                            Stock = 1,
                            Thumbnail = "https://picsum.photos/640/480/?image=123"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 4,
                            Description = "Aut possimus ullam nihil perferendis quia suscipit ea officia quia minus ullam optio quia iusto in aperiam laboriosam et sunt.",
                            Discount = 10.7128968009319610m,
                            Name = "Officia maxime qui.",
                            Price = 10.2294630488517990m,
                            Stock = 10,
                            Thumbnail = "https://picsum.photos/640/480/?image=892"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 5,
                            Description = "Pariatur reiciendis explicabo explicabo atque porro nostrum qui ab eum est ipsum soluta nesciunt voluptas quaerat sit placeat quos quae.",
                            Discount = 10.700605823518990m,
                            Name = "Totam reprehenderit quidem.",
                            Price = 10.8239505439176920m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=974"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 2,
                            Description = "Consequatur recusandae cupiditate unde vel optio molestias laborum accusantium quidem vel reiciendis aut laborum ut est et dignissimos saepe quasi.",
                            Discount = 10.6868273996221030m,
                            Name = "Ipsum dolorem voluptatem.",
                            Price = 10.8696908810500480m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=1056"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 6,
                            Description = "Error laborum quia ipsam omnis accusantium aut fugit vero eos ea maiores et incidunt ut eum recusandae sint neque non.",
                            Discount = 10.7630700737997280m,
                            Name = "Ut vel voluptatem.",
                            Price = 10.3512623041641260m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=1055"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 5,
                            Description = "Officia autem sunt totam rerum ex quae esse excepturi et molestiae vero animi ut autem excepturi dicta voluptates esse quidem.",
                            Discount = 10.9658666960736120m,
                            Name = "Explicabo reprehenderit quia.",
                            Price = 10.4536638727661520m,
                            Stock = 3,
                            Thumbnail = "https://picsum.photos/640/480/?image=300"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 4,
                            Description = "Dolor deserunt eaque praesentium harum necessitatibus non atque error saepe aut exercitationem amet illum accusamus et sunt nemo est sed.",
                            Discount = 10.3191427017185570m,
                            Name = "Id quibusdam et.",
                            Price = 10.9707505493288630m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=197"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 9,
                            Description = "Nesciunt fugit quis minima natus dolore harum et laudantium delectus modi quo nihil enim rerum adipisci consequatur quia qui quidem.",
                            Discount = 10.7820405423557580m,
                            Name = "Possimus libero dolorum.",
                            Price = 10.09768942422125930m,
                            Stock = 4,
                            Thumbnail = "https://picsum.photos/640/480/?image=735"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 6,
                            Description = "Voluptatem libero dolor debitis eius voluptates quia qui id qui id itaque sit hic ut quia vitae eveniet velit distinctio.",
                            Discount = 10.2482351862118740m,
                            Name = "Soluta eum praesentium.",
                            Price = 10.3729144508824280m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=1077"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 1,
                            Description = "Maxime velit quis debitis esse quia assumenda quibusdam amet ut dolores quibusdam maiores dolores officia doloribus iure excepturi qui voluptatem.",
                            Discount = 10.2481693552099960m,
                            Name = "Aperiam cupiditate vel.",
                            Price = 10.8122388724294670m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=330"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 8,
                            Description = "Odit tempora sunt sit eum rerum nihil adipisci provident vero cupiditate aut dolor quia recusandae id in et tempore debitis.",
                            Discount = 10.5717933799940130m,
                            Name = "Ipsum sunt ut.",
                            Price = 10.6598836517240310m,
                            Stock = 2,
                            Thumbnail = "https://picsum.photos/640/480/?image=290"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 7,
                            Description = "Dolorum consectetur est dolore vitae et est sapiente est enim velit ipsa autem reprehenderit blanditiis non doloribus odio ut quidem.",
                            Discount = 10.05181697991295580m,
                            Name = "Autem error et.",
                            Price = 10.3138153978222120m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=633"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 2,
                            Description = "Inventore omnis animi aut vel quia sunt laboriosam magnam ad molestiae ipsam corrupti aut delectus sunt quia harum dicta ut.",
                            Discount = 10.6413456027588550m,
                            Name = "Non et sed.",
                            Price = 10.1148794964490830m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=537"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 9,
                            Description = "Dolores a facere officiis fuga voluptatem ut asperiores impedit in distinctio officia qui fugit ad quo excepturi expedita voluptatem laboriosam.",
                            Discount = 10.6050183184468270m,
                            Name = "Molestiae sit similique.",
                            Price = 10.08724695820698840m,
                            Stock = 5,
                            Thumbnail = "https://picsum.photos/640/480/?image=439"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 8,
                            Description = "Aut blanditiis est qui voluptatem consequatur nulla nostrum cupiditate illo eligendi suscipit quasi ut vel aut ut dolores ducimus repellat.",
                            Discount = 10.0918059214445790m,
                            Name = "Reiciendis quam esse.",
                            Price = 10.3644227177670330m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=138"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 7,
                            Description = "Excepturi necessitatibus maxime facilis qui corrupti voluptatem aliquam autem non error vel enim maiores consectetur praesentium sapiente vel enim sed.",
                            Discount = 10.6398569651133650m,
                            Name = "Nulla deleniti necessitatibus.",
                            Price = 10.225187966239260m,
                            Stock = 9,
                            Thumbnail = "https://picsum.photos/640/480/?image=842"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 10,
                            Description = "Dolorem vero cum dolor cupiditate tenetur dolor harum enim quae id qui hic consequuntur perferendis omnis recusandae harum qui vel.",
                            Discount = 10.172801196189970m,
                            Name = "Nihil ab aut.",
                            Price = 10.9021512791058750m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=574"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 9,
                            Description = "Repellat fugit sed nemo iusto eos molestiae itaque provident iure nostrum ipsam sed iste voluptatem sint quia nobis ipsum aspernatur.",
                            Discount = 10.1305288389001640m,
                            Name = "Commodi nam officiis.",
                            Price = 10.6275262337306170m,
                            Stock = 7,
                            Thumbnail = "https://picsum.photos/640/480/?image=623"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 9,
                            Description = "Quasi quo id nesciunt nostrum voluptates quidem adipisci non ullam voluptatem consequatur optio architecto tempora perspiciatis laboriosam esse quia ut.",
                            Discount = 10.8672611284382930m,
                            Name = "Tempore voluptatibus et.",
                            Price = 10.02415109892569070m,
                            Stock = 8,
                            Thumbnail = "https://picsum.photos/640/480/?image=752"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 3,
                            Description = "Esse eius laborum omnis nesciunt omnis et illum repellendus dolores voluptatem exercitationem sint tenetur doloribus voluptates sed ea ea omnis.",
                            Discount = 10.154413615425310m,
                            Name = "Error et et.",
                            Price = 10.9019001852264160m,
                            Stock = 6,
                            Thumbnail = "https://picsum.photos/640/480/?image=211"
                        });
                });

            modelBuilder.Entity("IntroSEProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IntroSEProject.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("IntroSEProject.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("IntroSEProject.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("IntroSEProject.Models.SeatReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("SeatReservations");
                });

            modelBuilder.Entity("IntroSEProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailConfirmToken")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/753.jpg",
                            DateOfBirth = new DateTime(2023, 2, 1, 22, 46, 44, 241, DateTimeKind.Local).AddTicks(6121),
                            Email = "ClarkFadel.Stark@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Clark Fadel",
                            Gender = "Female",
                            Password = "DZBRHDGI6q",
                            PhoneNumber = "1-889-737-9865 x33749",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/76.jpg",
                            DateOfBirth = new DateTime(2023, 3, 22, 11, 31, 54, 702, DateTimeKind.Local).AddTicks(2616),
                            Email = "BethNicolas17@hotmail.com",
                            EmailConfirmed = false,
                            FullName = "Beth Nicolas",
                            Gender = "Female",
                            Password = "7JyPeJbP8k",
                            PhoneNumber = "1-666-934-7051 x29752",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/789.jpg",
                            DateOfBirth = new DateTime(2023, 2, 18, 8, 25, 23, 352, DateTimeKind.Local).AddTicks(1993),
                            Email = "AylaEbert74@hotmail.com",
                            EmailConfirmed = false,
                            FullName = "Ayla Ebert",
                            Gender = "Female",
                            Password = "FGtKv09y4J",
                            PhoneNumber = "(663) 951-5830 x4872",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/947.jpg",
                            DateOfBirth = new DateTime(2023, 7, 27, 11, 41, 12, 268, DateTimeKind.Local).AddTicks(6953),
                            Email = "EstevanBogisich.Skiles@yahoo.com",
                            EmailConfirmed = false,
                            FullName = "Estevan Bogisich",
                            Gender = "Female",
                            Password = "yNeq0uPIe4",
                            PhoneNumber = "1-713-316-9030",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1062.jpg",
                            DateOfBirth = new DateTime(2023, 1, 30, 2, 22, 9, 12, DateTimeKind.Local).AddTicks(5691),
                            Email = "PhilipPollich_Terry@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Philip Pollich",
                            Gender = "Male",
                            Password = "GR7yOwso6s",
                            PhoneNumber = "317.752.1611 x9359",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/49.jpg",
                            DateOfBirth = new DateTime(2023, 11, 3, 6, 29, 28, 917, DateTimeKind.Local).AddTicks(4890),
                            Email = "LibbieHeathcote.Bins14@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Libbie Heathcote",
                            Gender = "Male",
                            Password = "o4vdUhkpIn",
                            PhoneNumber = "319.502.8272 x48793",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1020.jpg",
                            DateOfBirth = new DateTime(2023, 11, 29, 1, 46, 38, 237, DateTimeKind.Local).AddTicks(240),
                            Email = "HildaGraham.Balistreri6@hotmail.com",
                            EmailConfirmed = false,
                            FullName = "Hilda Graham",
                            Gender = "Male",
                            Password = "1zF6OQAGJL",
                            PhoneNumber = "597-752-7924 x0122",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/109.jpg",
                            DateOfBirth = new DateTime(2023, 6, 6, 7, 52, 16, 241, DateTimeKind.Local).AddTicks(2860),
                            Email = "EulaliaBartell87@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Eulalia Bartell",
                            Gender = "Male",
                            Password = "_nP5wBstle",
                            PhoneNumber = "(315) 869-1332 x0488",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/88.jpg",
                            DateOfBirth = new DateTime(2023, 3, 26, 22, 4, 31, 804, DateTimeKind.Local).AddTicks(431),
                            Email = "PaoloMcCullough.Weimann17@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Paolo McCullough",
                            Gender = "Female",
                            Password = "I7RR7JTvse",
                            PhoneNumber = "541-747-8384",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1170.jpg",
                            DateOfBirth = new DateTime(2023, 10, 18, 8, 15, 58, 56, DateTimeKind.Local).AddTicks(5411),
                            Email = "AndreaneBogisich_Hintz@hotmail.com",
                            EmailConfirmed = false,
                            FullName = "Andreane Bogisich",
                            Gender = "Male",
                            Password = "SFATDQgzLK",
                            PhoneNumber = "238-766-1993",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("IntroSEProject.Models.CartItem", b =>
                {
                    b.HasOne("IntroSEProject.Models.Item", "Item")
                        .WithMany("CartItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntroSEProject.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntroSEProject.Models.Item", b =>
                {
                    b.HasOne("IntroSEProject.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IntroSEProject.Models.Order", b =>
                {
                    b.HasOne("IntroSEProject.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntroSEProject.Models.OrderItem", b =>
                {
                    b.HasOne("IntroSEProject.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntroSEProject.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IntroSEProject.Models.Payment", b =>
                {
                    b.HasOne("IntroSEProject.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntroSEProject.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntroSEProject.Models.Review", b =>
                {
                    b.HasOne("IntroSEProject.Models.OrderItem", "OrderItem")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntroSEProject.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntroSEProject.Models.SeatReservation", b =>
                {
                    b.HasOne("IntroSEProject.Models.Order", "Order")
                        .WithMany("SeatReservations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IntroSEProject.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IntroSEProject.Models.Item", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("IntroSEProject.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("SeatReservations");
                });

            modelBuilder.Entity("IntroSEProject.Models.OrderItem", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("IntroSEProject.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
